### ISSUE TITLE
Validating invalid ISBN 9786303025575 throws a PHP notice instead of an Exception

### ISSUE THREAD

**Issue by StefanGlaesser** [biblys/isbn#45]
An error occurred while attempting to format ISBN 9786303025575: Notice: Trying to access array offset on value of type null 

You can check it here:
https://www.isbn-check.de/checkisbn.pl?isbn=9786303025575&submit=testen&lang=de

**Comment by iwazaru** [comment]
After doing some research, I can answer your question. This ISBN is invalid because there is no ISBN range starting with `978-63…`. You can verify this manually by downloading [the official ISBN ranges file](https://www.isbn-international.org/range_file_generation) and searching for `978-63`.

You can also check this at https://www.loc.gov/publish/pcn/isbncnvt_pcn.html by trying to convert your ISBN while toggling the "Hyphenate ISBNs" checkbox. This is because knowing the ISBN range is necessary to guess the correct hyphen position. 

Anyway, you should't get PHP notice when validating an invalid ISBN, but an Exception with a clear message explaining why it is invalid. I will fix this in the next release.

**Comment by StefanGlaesser** [comment]
Hello,
I can confirm that version 2.5.0 works as expected:

It leaves wrong EANs untouched like here: 
https://www.buchfreund.de/de/d/e/9786303025575/billy-joel-live-from-long-island-vhs?bookId=47638591
With 2.4.0 we got here an uncatchable 500 error.

And it transforms EANs to ISBNs correctly like in this example:
https://www.buchfreund.de/de/d/e/9783499100048/schloss-gripsholm?bookId=97604571 

Best regards,
Stefan

**Comment by iwazaru** [comment]
Glad it works, thanks for your feedback.
